### ISSUE TITLE
custom-rust-server.sh not found

### ISSUE THREAD

**Issue by levi2m** [samrocketman/docker-compose-lgsm-rust-dedicated-server#10]
getting the following error on the first setup

using the latest versions of docker compose and already try on other desktops and OSs.

```
+ echo 'linuxgsm  ALL=(ALL) NOPASSWD:ALL'
++ id -u linuxgsm
+ lgsm_uid=1000
++ id -g linuxgsm
+ lgsm_gid=1000
+ '[' '!' 1000 = 1000 ']'
++ stat -c %U /home/linuxgsm
+ '[' '!' linuxgsm = linuxgsm ']'
++ stat -c %U /custom-maps
+ '[' '!' linuxgsm = linuxgsm ']'
+ python3 -m venv /home/linuxgsm/.venv
+ grep -F .venv /home/linuxgsm/.bash_profile
source /home/linuxgsm/.venv/bin/activate
+ grep -F .venv /home/linuxgsm/.bashrc
source /home/linuxgsm/.venv/bin/activate
++ stat -c %U /home/linuxgsm/.venv
+ '[' '!' linuxgsm = linuxgsm ']'
+ chown linuxgsm: /home/linuxgsm /home/linuxgsm/serverfiles /home/linuxgsm/serverfiles/oxide
+ chown -R linuxgsm: /home/linuxgsm/serverfiles/oxide/config
+ rm -f /home/linuxgsm/linuxgsm.sh
+ su - linuxgsm -c 'LINUX_GSM_VERSION="v20.4.1" /utils/custom-rust-server.sh'
-sh: 1: /utils/custom-rust-server.sh: not found
```

**Comment by samrocketman** [comment]
Need more info.  That definitely exists.  The host OSis Linux.  Are you on another OS such as windows?  Does your OS restrict execution on the path you have it cloned such as noexec mount option?

**Comment by joana-lima** [comment]
Got the same issue here, using Windows 10 OS as host.
Some changes to the docker-compose.yaml solved it for me.

Try as below:
` 
 [ . . . ]
        chown -R linuxgsm: /utils
        sed -i 's/\r$//' /utils/custom-rust-server.sh
        chmod +x /utils/custom-rust-server.sh
        su - linuxgsm -c "LINUX_GSM_VERSION=\"${LINUX_GSM_VERSION:-v20.4.1}\" /utils/custom-rust-server.sh"
    volumes:
[ . . . ]
      - ./utils/:/utils/:rw
[ . . . ]`
