### ISSUE TITLE
Permission denied was first displayed, and now it is no found.

### ISSUE THREAD

**Issue by sageded** [samrocketman/docker-compose-lgsm-rust-dedicated-server#17]
When it shows that there is no permission, I use the command ` chmod 777 utils`  to give utils permission, and it will become no found after being executed again.

begin
`lgsm_1  | + lgsm_gid=1000
lgsm_1  | + '[' '!' 1000 = 1000 ']'
lgsm_1  | ++ stat -c %U /home/linuxgsm
lgsm_1  | + '[' '!' linuxgsm = linuxgsm ']'
lgsm_1  | ++ stat -c %U /custom-maps
lgsm_1  | + '[' '!' linuxgsm = linuxgsm ']'
lgsm_1  | + python3 -m venv /home/linuxgsm/.venv
lgsm_1  | + grep -F .venv /home/linuxgsm/.bash_profile
lgsm_1  | source /home/linuxgsm/.venv/bin/activate
lgsm_1  | + grep -F .venv /home/linuxgsm/.bashrc
lgsm_1  | source /home/linuxgsm/.venv/bin/activate
lgsm_1  | ++ stat -c %U /home/linuxgsm/.venv
lgsm_1  | + '[' '!' linuxgsm = linuxgsm ']'
lgsm_1  | + chown linuxgsm: /home/linuxgsm /home/linuxgsm/serverfiles /home/linuxgsm/serverfiles/oxide
lgsm_1  | + chown -R linuxgsm: /home/linuxgsm/serverfiles/oxide/config
lgsm_1  | + rm -f /home/linuxgsm/linuxgsm.sh
lgsm_1  | + su - linuxgsm -c 'LINUX_GSM_VERSION="v20.4.1" /utils/custom-rust-server.sh'
lgsm_1  | -sh: 1: /utils/custom-rust-server.sh: Permission denied.`

after
`lgsm_1  | + lgsm_gid=1000
lgsm_1  | + '[' '!' 1000 = 1000 ']'
lgsm_1  | ++ stat -c %U /home/linuxgsm
lgsm_1  | + '[' '!' linuxgsm = linuxgsm ']'
lgsm_1  | ++ stat -c %U /custom-maps
lgsm_1  | + '[' '!' linuxgsm = linuxgsm ']'
lgsm_1  | + python3 -m venv /home/linuxgsm/.venv
lgsm_1  | + grep -F .venv /home/linuxgsm/.bash_profile
lgsm_1  | source /home/linuxgsm/.venv/bin/activate
lgsm_1  | + grep -F .venv /home/linuxgsm/.bashrc
lgsm_1  | source /home/linuxgsm/.venv/bin/activate
lgsm_1  | ++ stat -c %U /home/linuxgsm/.venv
lgsm_1  | + '[' '!' linuxgsm = linuxgsm ']'
lgsm_1  | + chown linuxgsm: /home/linuxgsm /home/linuxgsm/serverfiles /home/linuxgsm/serverfiles/oxide
lgsm_1  | + chown -R linuxgsm: /home/linuxgsm/serverfiles/oxide/config
lgsm_1  | + rm -f /home/linuxgsm/linuxgsm.sh
lgsm_1  | + su - linuxgsm -c 'LINUX_GSM_VERSION="v20.4.1" /utils/custom-rust-server.sh'
lgsm_1  | -sh: 1: /utils/custom-rust-server.sh: not found`

I used the instruction to confirm that the /utils/custom-rust-server.sh script does exist in the container.
`root@iZ2:/home# docker exec -it 46816e ls /utils
apply-settings.sh  custom-rust-server.sh  get-or-update-plugins.sh  monitor-rust-server.sh`

**Comment by sageded** [comment]
I'm sure that users who use linuxgsm can see the file "/utils/custom-rust-server.sh", but it prompts "not found".  when I copy the code in the file "custom-rust-server.sh" to "test.sh" and modify the execution file to "test.sh". It can be executed normally.

`        chmod +x /utils/*`
`        chmod +x /rust-environment.sh`
`        chown -R linuxgsm: /utils`
`        chown -R linuxgsm: /rust-environment.sh`
`        rm -f ~linuxgsm/linuxgsm.sh`
`        su - linuxgsm -c "LINUX_GSM_VERSION=\"${LINUX_GSM_VERSION:-v20.4.1}\" /utils/test.sh"`

run
`lgsm_1  | + chmod +x /utils/apply-settings.sh /utils/custom-rust-server.sh /utils/get-or-update-plugins.sh /utils/monitor-rust-server.sh /utils/test.sh`
`lgsm_1  | + chmod +x /rust-environment.sh`
`lgsm_1  | + chown -R linuxgsm: /utils`
`lgsm_1  | + chown -R linuxgsm: /rust-environment.sh`
`lgsm_1  | + rm -f /home/linuxgsm/linuxgsm.sh`
`lgsm_1  | + su - linuxgsm -c 'LINUX_GSM_VERSION="v20.4.1" /utils/test.sh'`
`lgsm_1  | + '[' -f ./linuxgsm.sh ']'`
`lgsm_1  | + '[' -n v20.4.1 ']'`
`lgsm_1  | + curl -fLo linuxgsm.sh https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/v20.4.1/linuxgsm.sh`

**Comment by samrocketman** [comment]
Can you describe more of your setup?  Are you using Docker engine from official repos?  What is your OS?

**Comment by sageded** [comment]
my OS is "Ubuntu 20.04 64". my docker version is "Docker version 25.0.1, build 29cf629". my docker-compose is "docker-compose version 1.25.0, build unknown"

**Comment by sageded** [comment]
> Can you describe more of your setup? Are you using Docker engine from official repos? What is your OS/Version?

my OS is "Ubuntu 20.04 64". my docker version is "Docker version 25.0.1, build 29cf629". my docker-compose is "docker-compose version 1.25.0, build unknown"

**Comment by samrocketman** [comment]
That’s similar to what I run.  Currently on Ubuntu 22.04 but I launched it find and launched previously with Ubuntu 20.04.  How are you starting it?

**Comment by sageded** [comment]
> That’s similar to what I run. Currently on Ubuntu 22.04 but I launched it fine and launched previously with Ubuntu 20.04. What command are you using while starting it?

I will place the project in the "/home/RestServer" path. I run it using the command "docker-compose up".

**Comment by sageded** [comment]
I think it's my system question. The sh file I created by myself can be executed by putting it in the container. Sh downloaded from the internet is put into a container and executed, and then it returns to no found.
