### ISSUE TITLE
/utils/custom-rust-server.sh: not found

### ISSUE THREAD

**Issue by VivekGupta137** [samrocketman/docker-compose-lgsm-rust-dedicated-server#20]
lgsm-1  | + su - linuxgsm -c 'LINUX_GSM_VERSION="v20.4.1" /utils/custom-rust-server.sh'                                                                                                      
lgsm-1  | -sh: 1: /utils/custom-rust-server.sh: not found

**Comment by samrocketman** [comment]
I recommend following the README
