### ISSUE TITLE
How can I setup the rust+ app

### ISSUE THREAD

**Issue by Gr3gorywolf** [samrocketman/docker-compose-lgsm-rust-dedicated-server#21]
Im trying to setup the rust+ app, trying to set the port and ip from the RCON console but the  settings return to the default value after server restart so im not able to setup any custom server config even if I run `server.writecfg` the changes are not being persisted

**Comment by samrocketman** [comment]
I've not used Rust+ before so I'm not sure.  If I find anything I'll follow up.

**Comment by Gr3gorywolf** [comment]
Im just trying to save a setting such as decay.scale 0 but somehow it doesn't get persisted once I restart the server

**Comment by samrocketman** [comment]
There's nothing preventing that persistence as far as I know.  Here is where server config is edited but it is not overwritten.

https://github.com/samrocketman/docker-compose-lgsm-rust-dedicated-server/blob/d585fae75778595c3344d26149c83a9e872f5a92/utils/apply-settings.sh#L19-L27

**Comment by samrocketman** [comment]
Did you end up figuring out Rust+?

**Comment by samrocketman** [comment]
According to the docs you need to expose an additional port over the internet and docker https://wiki.facepunch.com/rust/rust-companion-server

According to these docs expose 28063 in docker compose file.

https://github.com/samrocketman/docker-compose-lgsm-rust-dedicated-server/blob/c2661ab063dca5871b0737595594a8a1f4552a4c/docker-compose.yml#L70-L73

You will need to take additional steps to expose your server to the internet.
