### ISSUE TITLE
[ FAIL ] Installing rustserver: Ownership issues found

### ISSUE THREAD

**Issue by vipje** [samrocketman/docker-compose-lgsm-rust-dedicated-server#22]
+ ./rustserver install

[ FAIL ] Installing rustserver: Ownership issues found

Information! The current user (linuxgsm) does not have ownership of the following files:

tee: /home/linuxgsm/log/script/rustserver-script.log: No such file or directory

User  Group  File

root  root   /home/linuxgsm/serverfiles/HarmonyConfig

root  root   /home/linuxgsm/serverfiles/HarmonyConfig/.gitignore

root  root   /home/linuxgsm/serverfiles/HarmonyMods

root  root   /home/linuxgsm/serverfiles/HarmonyMods/.gitignore

Information! please see https://docs.linuxgsm.com/support/faq#fail-starting-game-server-permission-issues-found

[WARN  tini (7)] Tini is not running as PID 1 and isn't registered as a child subreaper.

Zombie processes will not be re-parented to Tini, so zombie reaping won't work.

To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.

+ apt-get update

Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease

Hit:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease

Hit:3 http://archive.ubuntu.com/ubuntu focal-backports InRelease

Hit:4 https://deb.nodesource.com/node_16.x focal InRelease

Hit:5 http://security.ubuntu.com/ubuntu focal-security InRelease

Reading package lists...

**Comment by samrocketman** [comment]
Need more info; this works spinning up on Ubuntu 22.04.

**Comment by vipje** [comment]
i have docker running on a windows server 2022
docker version : 27.2. 0
Context: desktop-linux
Architecture: x86_64
Docker Compose version : v2.29. 2-desktop. 2

If you need other details let me know and i will give them to you.

**Comment by TimKraemer** [comment]
same issue - debian, docker compose v2.29.7

**Comment by samrocketman** [comment]
@TimKraemer something seems wrong with your setup on your end.

@vipje did you verify the repository is cloned into a filesystem with ext4?  These scripts aren't designed to be operated from NTFS filesystem so it's possible you're running into an issue with that.  Look at the docker-compose.yml file and note the volumes being mounted.

# My system

* Filesystem: ext4
* OS: Ubuntu 22.04.5 LTS
* Docker engine: 27.3.1 (please note I'm running normal docker and NOT rootless docker.  This likely will not work if you're running docker compose with rootless docker.

Other unrelated specs: 8 thread core i7 CPU (2011 model), 32GB of RAM, and (unused by the server) AMD RX5700XT

# Other notes

I performed a fresh git clone and I ran `docker compose up -d` and the server came up fine just now.  No modifications to the source other than pulling down the patches I merged today which are unrelated to this issue.

# connect

I was able to F1 console and

```
client.connect localhost:28015
```

# start up logs

![Screenshot taken at 2024-10-06_12-18-32](https://github.com/user-attachments/assets/1b2e8bc8-2c10-4802-8663-f69e3ddf5dae)

# rcon password

![Screenshot taken at 2024-10-06_12-20-30](https://github.com/user-attachments/assets/30a52456-8db9-43eb-a254-fbc410414e82)

# rcon admin panel

![Screenshot taken at 2024-10-06_12-21-43](https://github.com/user-attachments/assets/d906eb3e-752d-49cf-8147-58f23ba24926)

**Comment by samrocketman** [comment]
![Screenshot taken at 2024-10-07_15-15-15](https://github.com/user-attachments/assets/45a4996f-b905-4e04-9110-a00bef2175e4)

Play testing solo on localhost it seems to operate fine.

**Comment by samrocketman** [comment]
I'll close this issue by Oct 14th if I don't hear back.

 @vipje we can reopen this issue if you still write back at a later time.

@TimKraemer feel free to open a new issue if that happens and you still want support.

**Comment by TK-3375** [comment]
Adding to this issue : I am facing the same problem : fresh container install of debian 12 (on proxmox), I get those in the logs when starting the server : docker compose up -d 

```
lgsm-1  | + chmod 755 linuxgsm.sh
lgsm-1  | + '[' -x ./rustserver ']'
lgsm-1  | + yes Y
lgsm-1  | + ./rustserver install
[ FAIL ] Installing rustserver: Ownership issues found
lgsm-1  | Information! The current user (linuxgsm) does not have ownership of the following files:
lgsm-1  | tee: /home/linuxgsm/log/script/rustserver-script.log: No such file or directory
lgsm-1  | User  Group  File
lgsm-1  | root  root   /home/linuxgsm/serverfiles/HarmonyMods
lgsm-1  | root  root   /home/linuxgsm/serverfiles/HarmonyMods/.gitignore
lgsm-1  | root  root   /home/linuxgsm/serverfiles/HarmonyConfig
lgsm-1  | root  root   /home/linuxgsm/serverfiles/HarmonyConfig/.gitignore
lgsm-1  | 
lgsm-1  | Information! please see https://docs.linuxgsm.com/support/faq#fail-starting-game-server-permission-issues-found
```

Apparently the fix is to change the files owner, but I dont' know how to do that in docker though. Ideas ?

**Comment by samrocketman** [comment]
I’m not familiar with proxmox.

Try changing this line https://github.com/samrocketman/docker-compose-lgsm-rust-dedicated-server/blob/c2661ab063dca5871b0737595594a8a1f4552a4c/docker-compose.yml#L57

To

    chown linuxgsm: -R /home/lgsm

Generally this is a bad practice.  You should probably use a find command, instead, but I am not available to give you a better command at the moment. Let me know if this works.
