### ISSUE TITLE
Plugins downloaded from plugins.txt do not load in Oxide because of case mismatch

### ISSUE THREAD

**Issue by Ovaru** [samrocketman/docker-compose-lgsm-rust-dedicated-server#24]
I am not able to connect to RCON whether through the web page or through ssh. Is there a way to set my self as the server owner without access to either of these. I put my uuid64 and username in the user config in the shell but got nothing

**Comment by samrocketman** [comment]
RCON is exposed with a randomly generated password.  Did you obtain the password by running the admin script?

```bash
./admin/get-rcon-pass.sh
```

**Comment by Ovaru** [comment]
Yes I was able to give myself permissions but now my oxide mods are not loading even though I added the names to the /mod-configs/plugins.txt

it said the mods were loaded when I ran the .admin script to reload them but the oxide.plugins command is showing this.

```
 > oxide.plugins
Listing 7 plugins:
  01 adminpanel - Failed to compile: Plugin filename adminpanel.cs must match the main class AdminPanel (should be AdminPanel.cs)
  02 deathnotes - Unloaded
  03 imagelibrary - Failed to compile: Plugin filename imagelibrary.cs must match the main class ImageLibrary (should be ImageLibrary.cs)
  04 nogivenotices - Failed to compile: Plugin filename nogivenotices.cs must match the main class NoGiveNotices (should be NoGiveNotices.cs)
  05 nteleportation - Failed to compile: Plugin filename nteleportation.cs must match the main class NTeleportation (should be NTeleportation.cs)
  06 stacksizecontroller - Failed to compile: Plugin filename stacksizecontroller.cs must match the main class StackSizeController (should be StackSizeController.cs)
  07 whitelist - Failed to compile: Plugin filename whitelist.cs must match the main class Whitelist (should be Whitelist.cs) 

```

Is there another thing I should be doing to "automatically" download the plugins from Umod?

**Comment by samrocketman** [comment]
It has been a long time since I've messed with the plugins.  According to the errors the cs files must match the class names.

So fix them for now:

```bash
mv adminpanel.cs AdminPanel.cs
mv nogivenotices.cs NoGiveNotices.cs
... etc
```

How did you populate plugins.txt?

**Comment by samrocketman** [comment]
I can patch it to detect the name in the CS files and auto-rename.

**Comment by Ovaru** [comment]
Right now it's set to like the read me stated but I might be interpreting it wrong

```imagelibrary
stacksizecontroller
whitelist
deathnotes
adminpanel
nteleportation
nogivenotices
godmode
```

Do I have to restart the server or just run the plugin reload script to add new plugins?

**Comment by samrocketman** [comment]
I'm about to push a patch based on your plugins.txt.  I'll let you know next steps when patch is up.

**Comment by Ovaru** [comment]
great thank you

**Comment by samrocketman** [comment]
It took a couple of server restarts to verify my fixes (and fix bugs in my fixes) but it is done.

![image](https://github.com/user-attachments/assets/d8b98bee-af7c-4b92-9694-f086af2ea84b)

# Your next steps

### 1. Go to RCON and run `save` in the console

It is also prudent to run `./admin/backup/create-backup.sh` to create a backup after you've saved.

### 2. Remove plugins before restart

You'll need to pull the changes and restart.  But before you restart delete the old plugins manually.

```bash
git pull https://github.com/samrocketman/docker-compose-lgsm-rust-dedicated-server/ main
./admin/shell.sh
# and from within admin shell
find serverfiles/oxide/plugins -type f -name '*.cs' -exec rm {} +
```

Exit the admin shell and restart the server.

### 3. Restart the server

```bash
docker compose down
docker compose up -d
```

You can run `docker compose logs -f` to follow the logs (ctrl+c to cancel).

**Comment by samrocketman** [comment]
Actually, after some testing it doesn't require a restart.

```bash
./admin/shell.sh
# and from within admin shell
find serverfiles/oxide/plugins -type f -name '*.cs' -exec rm {} +
/utils/get-or-update-plugins.sh
```

The rust console in RCON showed that oxide gracefully handled loading the plugins.

**Comment by Ovaru** [comment]
Works great thank you!
