### ISSUE TITLE
rcon pass not available

### ISSUE THREAD

**Issue by RussIT99** [samrocketman/docker-compose-lgsm-rust-dedicated-server#4]
sudo ./get-rcon-pass.sh
RCON password: cat: rcon_pass: No such file or directory

Visit one of the following web RCON clients:

- http://facepunch.github.io/webrcon address 127.0.0.1:28016
- http://rcon.io/login address 127.0.0.1 port 28016

**Comment by RussIT99** [comment]
Sorry it does work when your in the admin directory

**Comment by noahhaon** [comment]
Hi, this still doesn't seem to work whether or not I'm in the admin directory.

**Comment by noahhaon** [comment]
The issue was missing python in the lsgm image, just needed to add it to the docker-compose.yml
