### ISSUE TITLE
python error during docker image startup

### ISSUE THREAD

**Issue by roygkov** [samrocketman/docker-compose-lgsm-rust-dedicated-server#5]
Hi there, I'm facing w/ a issue /utils/apply-settings.sh: line 60: python: command not found

docker-compose-lgsm-rust-dedicated-server-lgsm-1  | =================================
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | LinuxGSM_
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | by Daniel Gibbs
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Game: Rust
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Website: https://linuxgsm.com
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Contributors: https://linuxgsm.com/contrib
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Sponsor: https://linuxgsm.com/sponsor
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | =================================
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | 
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Server Directory
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | =================================
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Warning! A server is already installed here.
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | /home/linuxgsm
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | 
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | 
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Creating log directories
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | =================================
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | installing log dir: /home/linuxgsm/log...OK
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | installing LinuxGSM log dir: /home/linuxgsm/log/script...OK
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | creating LinuxGSM log: /home/linuxgsm/log/script/rustserver-script.log...OK
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | installing console log dir: /home/linuxgsm/log/console...OK
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | creating console log: /home/linuxgsm/log/console/rustserver-console.log...OK
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | 
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Checking Dependencies
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | =================================
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | curl
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | wget
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | ca-certificates
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | file
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | bsdmainutils
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | util-linux
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | python3
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | tar
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | bzip2
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | gzip
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | unzip
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | binutils
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | bc
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | jq
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | tmux
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | netcat
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | lib32gcc1
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | lib32stdc++6
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | steamcmd
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | lib32z1
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Information! Required dependencies already installed.
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | 
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Installing SteamCMD
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | =================================
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Information! SteamCMD is already installed...OK
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | 
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Installing Rust Server
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | =================================
[ START ] Installing rustserver: 
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Complete! Installing rustserver: 
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | 
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | =================================
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | 
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Downloading Rust Configs
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | =================================
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | default configs from https://github.com/GameServerManagers/Game-Server-Configs
copying server.cfg config file.
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | 
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Config File Locations
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | =================================
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Game Server Config File: /home/linuxgsm/serverfiles/server/rustserver/cfg/server.cfg
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | LinuxGSM Config: /home/linuxgsm/lgsm/config-lgsm/rustserver
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Documentation: https://docs.linuxgsm.com/configuration/game-server-config
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | 
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | 
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | LinuxGSM Stats
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | =================================
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Assist LinuxGSM development by sending anonymous stats to developers.
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | More info: https://docs.linuxgsm.com/configuration/linuxgsm-stats
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | The following info will be sent:
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | * game server
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | * distro
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | * game server resource usage
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | * server hardware info
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Information! Stats setting is now enabled in common.cfg.
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | 
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | =================================
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Install Complete!
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | 
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | To start server type:
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | ./rustserver start
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | 
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | + grep rustoxide lgsm/mods/installed-mods.txt
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | + ./rustserver mods-update
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Applying server settings from rust-environment.sh:
docker-compose-lgsm-rust-dedicated-server-lgsm-1  |     EAC Disabled.
docker-compose-lgsm-rust-dedicated-server-lgsm-1  |     servername="Rust"
docker-compose-lgsm-rust-dedicated-server-lgsm-1  |     maxplayers=50
docker-compose-lgsm-rust-dedicated-server-lgsm-1  |     worldsize=3000
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | /utils/apply-settings.sh: line 60: python: command not found
[ INFO ] Updating mods rustserver: Update addons/mods: 1 addons/mods will be updated
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | 	* Oxide for Rust (overwrite)
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | 
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | ==> Updating Oxide for Rust
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | creating mod download directory /home/linuxgsm/lgsm/mods/tmp...OK
######################################################################## 100.0%        #=#=#                                                                         
extracting Oxide.Rust-linux.zip...OK
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | building rustoxide-files.txt...OK
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | copying Oxide for Rust to /home/linuxgsm/serverfiles...OK
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | tidy up rustoxide-files.txt...OK
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | clearing mod download directory /home/linuxgsm/lgsm/mods/tmp...OK
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | 
[  OK  ] Updating mods rustserver: Mods update complete
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | + '[' '!' -f serverfiles/RustDedicated_Data/Managed/Oxide.Ext.RustEdit.dll ']'
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | + sudo rm -f /etc/sudoers.d/lgsm
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | + lgsm_cfg=lgsm/config-lgsm/rustserver/rustserver.cfg
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | + grep -F -- /utils/apply-settings.sh lgsm/config-lgsm/rustserver/rustserver.cfg
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | if [ ! "$1" = docker ]; then /utils/apply-settings.sh; source lgsm/config-lgsm/rustserver/rustserver.cfg docker; fi
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | + /utils/get-or-update-plugins.sh
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | No plugins upgraded.
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | No new plugins.
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | No plugins deleted.
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | No custom plugins found.
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | + ./rustserver start
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | + /utils/monitor-rust-server.sh
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Monitoring RustDedicated for automatic restart.
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | Applying server settings from rust-environment.sh:
docker-compose-lgsm-rust-dedicated-server-lgsm-1  |     EAC Disabled.
docker-compose-lgsm-rust-dedicated-server-lgsm-1  |     servername="Rust"
docker-compose-lgsm-rust-dedicated-server-lgsm-1  |     maxplayers=50
docker-compose-lgsm-rust-dedicated-server-lgsm-1  |     worldsize=3000
docker-compose-lgsm-rust-dedicated-server-lgsm-1  | /utils/apply-settings.sh: line 60: python: command not found
[ FAIL ] Starting rustserver: executable was not found

do you have any idea what might be the root cause of this issue?
best regards,

**Comment by flowl** [comment]
I noticed the same, I think `python` is not available while `python3` is.
You could symlink one to the other and it should work.

**Comment by samrocketman** [comment]
I could add some better detection for python3.  As of right now the script assumes python.

If you're on python3 you can do the following before launching the docker image.

```
python3 -m venv /tmp/venv
source /tmp/venv/bin/activate
docker-compose up -d
```

**Comment by samrocketman** [comment]
@roygkov @flowl python 3 support added and bugs fixed.  Thanks for reporting.
