### ISSUE TITLE
How to set ownerid?

### ISSUE THREAD

**Issue by flowl** [samrocketman/docker-compose-lgsm-rust-dedicated-server#6]
The rcon stuff does not work. Browser reject `ws` sockets (only secure `wss` works).

I put my uuid64 and my name in `serverfiles/server/rustserver/cfg/users.cfg` like

    ownerid base64uuid "Username"

and restarted the server, but it doesn't grant me admin access.

**Comment by flowl** [comment]
I picked the wrong 64 id, using the correct one (from the logs) worked.

**Comment by Ovaru** [comment]
how do you get to 

`serverfiles/server/rustserver/cfg/users.cfg` 

to enter in 

`ownerid base64uuid "Username"`

RCON is also not working for me

**Comment by Ovaru** [comment]
I found the file but now I am unable to join the server
